language: python
python:
  - "3.7"
addons:
  postgresql: "9.5"
services:
  - postgresql
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database gsevpt_tests;' -U postgres && psql -c 'create extension postgis;' -d gsevpt_tests -U postgres
script:
  - pytest